### ISSUE TITLE
Before call world:update() we can't access box:enter('...')

### ISSUE THREAD

**Issue by endlesstravel** [SSYGEA/windfield#10]
I use love 0.10.2 (32bit)
![image](https://user-images.githubusercontent.com/10757838/32216091-fa137f8a-be5e-11e7-9353-db5baf0355f6.png)

![image](https://user-images.githubusercontent.com/10757838/32216140-265d2122-be5f-11e7-9690-d0d8aea222a7.png)

**Comment by flamendless** [comment]
This is also a problem i encounter

**Comment by flamendless** [comment]
Put world: update first before using any windfield function

**Comment by a327ex** [comment]
I fixed this. You don't need to put world:update before calling any windfield functions anymore.

**Comment by flamendless** [comment]
Was the documentation also changed?

**Comment by a327ex** [comment]
There's no need to change the documentation since you don't need to do anything differently. You can call world:update before or after other windfield calls now.

**Comment by flamendless** [comment]
Okay, also, when I call world update in two objects that are processed at the same time, the physics is doubled. Ex:
World update in player and world update in enemy

**Comment by a327ex** [comment]
You should call world:update once per frame. You shouldn't call it once per entity.
