### ISSUE TITLE
Non-existent methods World:getBodies and Body:getFixtures called.

### ISSUE THREAD

**Issue by guird** [SSYGEA/windfield#19]
I don't know why I'm having this problem when no one else is, but these methods of love.physics.World are nil (hence resulting in a crash). I can't find a trace of them on the love2d physics documentation either. World:getBodies seems to have an extant version: World:getBodyList, so I was able to get around this by editing init.lua. however, Body:getFixtures does not seem to have this, there doesn't seem to be a way to get a fixture from a body. 

i'm using lua 5.1 and love2d 0.10.2

Thanks!

**Comment by Skeletonxf** [comment]
Love 11 renamed some functions (6a4a6003). You will need to update to love 11 or switch to an older version of this project to continue using love 10.

**Comment by guird** [comment]
Ah thank you, that explains. Guess the love docs hadn't been updated yet, but windfield was ahead of that curve.
