### ISSUE TITLE
Adding width to line colliders

### ISSUE THREAD

**Issue by WoolDoughnut310** [SSYGEA/windfield#30]
Would there be any way to add width to line colliders like how ```love.graphics.setLineWidth``` would be called?

EDIT: it won't be able to work using rectangle colliders and setting the angle since the offset is in the centre.

**Comment by davisdude** [comment]
You could emulate the line width with polygons, or just two parallel line segments depending on how wide the line is and how exact you want to be. You could do it like this, for instance: if the line width is `w`, you can get the angle perpendicular to the line, then go `w/2` units along that perpendicular line in either direction to get the bounding box for the line.

E.g.

```lua
-- Returns p1x, p1y, p2x, p2y, p3x, p3y, p4x, p4y where p1 and p2 are one part
-- of the line segment (e.g. the "left side") and p3 and p4 are the other part
local function wideLineSegment( w, x1, y1, x2, y2 )
	local vec = mlib.vec2.new( x1 - x2, y1 - y2 )
	local perp = mlib.vec2.perpendicular( vec )
	local unit = mlib.vec2.normalize( perp )

	local dx, dy = unit.x * w / 2, unit.y * w / 2
	return x1 - dx, y1 - dy,
	       x2 - dx, y2 - dy,
	       x1 + dx, y1 + dy,
	       x2 + dx, y2 + dy
end
```

**Comment by WoolDoughnut310** [comment]
it worked, thanks!
