### ISSUE TITLE
Debug drawing doesn't represent location of secondary fixtures. 

### ISSUE THREAD

**Issue by Muzz** [SSYGEA/windfield#5]
Debug drawing doesn't represent location of secondary fixtures. 

Repro. 

  self.collision = world:newRectangleCollider(x or 100, y or 100, 5, 70, {collision_class = 'Arrow'})
  self.collision.body:setFixedRotation(false)

  self.collision.fixtures['main']:setRestitution(0.6)
  self.collision.body:setLinearVelocity(1000_vec.x,1000_vec.y)
  self.collision.body:setAngle(math.deg(math.atan2(vec.y,vec.x))+90 or 90)

  -- there is a bug here that doesn't draw the debug correctly for added shapes.
  self.collision:addShape("head", "CircleShape", 0,-70,10)

**Comment by a327ex** [comment]
Fixed. You should add the shape with `y = -35` though, because it's always local in relation to the center of the body.
