### ISSUE TITLE
Incompatible licensing

### ISSUE THREAD

**Issue by Skeletonxf** [SSYGEA/windfield#7]
From the readme documentation this library looks really useful but I don't think you can have this library under MIT in its current state.

The dependency in this project called mlib is licensed under GPL2 which, being copyleft, would require this entire project to be licensed under GPL yet this project appears licensed under MIT. From a brief look at the source code it seems that mlib is only needed for the queryCircle/Rectangele/PolygonArea methods though within these the library is used for several things. I think this means you can either try to remove the dependency by writing your own drop in replacement for the methods you were using in the library to keep this project MIT licensed, or should comply with the licensing requirements of GPL to use the mlib library and relicense the project GPL

**Comment by a327ex** [comment]
I didn't notice mlib was GPL. I'll just change that library then. I can implement those functions myself or probably find them from another library since they aren't that many. Thanks for pointing it out.

**Comment by davisdude** [comment]
The license isn't that big a deal. I honestly just chose the first one I
saw, since I wasn't that well informed when I started writing it. You can
go ahead and use it. I'm rewriting it anyway, which will probably involve a
change to the mit license.

**Comment by davisdude** [comment]
The module is actually currently licensed under zlib, this is just a pretty old version of the library, so it's not really that much of an issue

**Comment by a327ex** [comment]
Oh, okay. That makes it easier I'll just update it to a more current version. Thanks!
